### ISSUE TITLE
create the comic by session

### ISSUE THREAD

**Issue by tritranduc** [Folody-Team/Shartube#10]
example :
    - one user 
      -- comic 1
        --- session 1
          ----- chap 1
      -- comic 2
        --- session 1
          ----- chap 1

**Comment by CookieGMVN** [comment]
Hmmm có ý tưởng hay hơn
- User
-- Comic
--- Section
---- Chapter

**Comment by tritranduc** [comment]
![image](https://user-images.githubusercontent.com/72681678/180650333-61600bfd-5e18-4e17-8f3f-6b115056484b.png)

**Comment by tritranduc** [comment]
session success
